# Generated by Django 4.1 on 2023-01-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoquizapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
